import { createServer } from "node:http";
import { readFile, mkdir } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(import.meta.url);
const { chromium } = require("playwright");
const root = path.resolve(import.meta.dirname, "..", "..");
const webRoot = path.join(root, "src", "CodexBridge.Entitlement.Server", "wwwroot", "admin");
const output = path.join(root, "docs", "acceptance", "screenshots", "m4-entitlements");
await mkdir(output, { recursive: true });
const licenses=[{licenseId:"lic_1",userId:"user-1",hostId:"host-1",deviceId:"device-1",plan:"pro",expiresAt:"2026-09-17T00:00:00Z",revoked:false}];
const server=createServer(async(request,response)=>{const url=new URL(request.url,"http://localhost");if(url.pathname.startsWith("/api/")){if(request.headers["x-codexbridge-admin-token"]!=="A".repeat(32)){response.writeHead(401,{"Content-Type":"application/json"});return response.end('{"error":"admin_unauthorized"}')}if(url.pathname==="/api/v1/admin/licenses"&&request.method==="GET")return json(response,licenses);if(url.pathname==="/api/v1/admin/invites")return json(response,{code:"CDB-ONE-TIME-CODE"});if(url.pathname==="/api/v1/admin/grants")return json(response,{refreshToken:"ONE-TIME-REFRESH"});if(url.pathname.startsWith("/api/v1/admin/licenses/")&&request.method==="DELETE"){licenses[0].revoked=true;response.writeHead(204);return response.end()}response.writeHead(404);return response.end()}try{const name=url.pathname.endsWith("/")?"index.html":path.basename(url.pathname);const ext=path.extname(name);const content=await readFile(path.join(webRoot,name));response.writeHead(200,{"Content-Type":ext===".css"?"text/css":ext===".js"?"text/javascript":"text/html"});response.end(content)}catch{if(!response.headersSent)response.writeHead(404);response.end()}});function json(response,value){response.writeHead(200,{"Content-Type":"application/json"});response.end(JSON.stringify(value))}
await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const base=`http://127.0.0.1:${server.address().port}/admin/`;const browser=await chromium.launch({channel:"chrome",headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto(base);await page.locator("#admin-token").fill("wrong-token-value-that-is-long-enough");await page.locator("#login-form button").click();await page.locator("#login-error").filter({hasText:"无效"}).waitFor();await page.locator("#admin-token").fill("A".repeat(32));await page.locator("#login-form button").click();await page.locator("#console-view:visible").waitFor();await page.locator("#invite-form button").click();await page.locator("#result-value").filter({hasText:"CDB-ONE-TIME-CODE"}).waitFor();await page.keyboard.press("Escape");page.once("dialog",dialog=>dialog.accept());await page.locator(".danger").click();await page.locator(".state.revoked").waitFor();const desktop=await page.evaluate(()=>({overflow:document.body.scrollWidth>innerWidth,local:localStorage.length,session:sessionStorage.length,rows:document.querySelectorAll("tbody tr").length,revoked:document.body.innerText.includes("已撤销")}));if(desktop.overflow||desktop.local||desktop.session||desktop.rows!==1||!desktop.revoked)throw new Error(`desktop admin acceptance failed: ${JSON.stringify(desktop)}`);await page.screenshot({path:path.join(output,"admin-1440x900.png"),fullPage:true});await page.close();const mobile=await browser.newPage({viewport:{width:390,height:844}});await mobile.goto(base);await mobile.locator("#admin-token").fill("A".repeat(32));await mobile.locator("#login-form button").click();await mobile.locator("#console-view:visible").waitFor();const mobileState=await mobile.evaluate(()=>({bodyOverflow:document.body.scrollWidth>innerWidth,buttons:[...document.querySelectorAll("button")].filter(button=>button.offsetParent).every(button=>button.getBoundingClientRect().height>=36)}));if(mobileState.bodyOverflow||!mobileState.buttons)throw new Error(`mobile admin acceptance failed: ${JSON.stringify(mobileState)}`);await mobile.screenshot({path:path.join(output,"admin-390x844.png"),fullPage:true});await mobile.close();process.stdout.write(JSON.stringify({adminAuth:true,invite:true,revoke:true,noTokenPersistence:true,desktop:true,mobile:true,screenshots:2})+"\n")}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
